Repository PotentialRadar/PR-Front, pull requests merged in 2025-08, with the labels that each got.

#26 Feat/mypage user edit my info
  src/App.vue
  src/api/axios.js
  src/api/login.js
  src/api/user.js
  src/components/layout/AppHeader.vue
  src/constants/parts.js
  src/main.js
  src/router/index.js
  src/stores/userStore.js
  src/views/EmailLoginPage.vue
  src/views/OAuth2Succcess.vue
  src/views/ProfileEditPage.vue
  src/views/SignUpPage.vue
Labels: ✨ 개선 (enhancement), 🛠 리팩토링 (refactoring)

#29 feat:make .env
  src/api/axios.js
  src/components/homeComponents/ProjectSection.vue
  src/components/projectComponents/TeamMemberRecommendation.vue
  src/constants/oauth.js
  vite.config.js
Labels: 🛠 리팩토링 (refactoring)

#30 Fix/projectcrud댓글
  src/App.vue
  src/api/axios.js
  src/api/projects.js
  src/api/user.js
  src/components/common/TechStackSelector.vue
  src/components/homeComponents/ProjectSection.vue
  src/components/projectComponents/CommentItem.vue
  src/components/projectComponents/PaginationComponent.vue
  src/components/projectComponents/ProjectCard.vue
  src/components/projectComponents/ProjectComment.vue
  src/composables/useFormValidation.js
  src/composables/useProjects.js
  src/constants/parts.js
  src/views/FavoritesPage.vue
  src/views/MyProjectListPage.vue
  src/views/ProjectCreatePage.vue
  src/views/ProjectDetailPage.vue
  src/views/ProjectListPage.vue
  src/views/ProjectManagePage.vue
Labels: ✨ 개선 (enhancement), 🛠 리팩토링 (refactoring)

#31 feat: 로그인 상태 기반 AI 추천 및 AI 추천 헤더 추가
  src/App.vue
  src/components/common/PageHeader.vue
  src/components/common/TechStackModal.vue
  src/components/homeComponents/ProjectSection.vue
  src/components/layout/AppHeader.vue
  src/components/projectComponents/TeamInviteModal.vue
  src/main.js
  src/router/index.js
  src/stores/userStore.js
  src/style.css
  src/views/AIRecommendationsPage.vue
  src/views/EmailLoginPage.vue
  src/views/OAuthSuccess.vue
  src/views/PortfolioListPage.vue
  src/views/ProjectCreatePage.vue
  src/views/ProjectDetailPage.vue
  src/views/ProjectListPage.vue
Labels: 🐞 버그 (bug), ✨ 개선 (enhancement), 🎨 디자인 (design)

#37 feat: notification 기능 구현
  package.json
  src/App.vue
  src/components/layout/AppHeader.vue
  src/composables/useNotifications.js
  src/stores/userStore.js
  src/views/ProjectDetailPage.vue
Labels: ✨ 개선 (enhancement)

#39 Feat/search
  src/api/search.js
  src/components/common/SearchableMultiSelect.vue
  src/components/layout/AppHeader.vue
  src/components/projectComponents/EnhancedSearchSection.vue
  src/components/projectComponents/SearchSection.vue
  src/stores/techTagStore.js
  src/views/PortfolioListPage.vue
  src/views/ProjectDetailPage.vue
  src/views/ProjectListPage.vue
Labels: ✨ 개선 (enhancement), 🛠 리팩토링 (refactoring), 🎨 디자인 (design)

#41 Feat/portfolio
  package.json
  src/api/axios.js
  src/api/portfolio.js
  src/api/user.js
  src/components/portfolio/ProjectSelectionModal.vue
  src/components/portfolioComponents/CareerTimeline.vue
  src/components/portfolioComponents/ProjectsSection.vue
  src/components/portfolioComponents/ReviewSection.vue
  src/components/portfolioComponents/SkillsSection.vue
  src/router/index.js
  src/utils/portfolioMapper.js
  src/views/MyPortfolioPage.vue
  src/views/PortfolioListPage.vue
  src/views/PortfolioPage.vue
  src/views/PortfolioProjectsPage.vue
  src/views/ProfileEditPage.vue
Labels: 🐞 버그 (bug)

#42 Fix/project(create)
  src/api/projects.js
  src/components/projectComponents/ProjectCard.vue
  src/components/projectComponents/ProjectWorkContent.vue
  src/views/ProjectCreatePage.vue
  src/views/ProjectDetailPage.vue
Labels: 🐞 버그 (bug)

#43 Feat/search portfolio
  src/api/search.js
  src/components/layout/AppHeader.vue
  src/components/projectComponents/EnhancedSearchSection.vue
  src/components/projectComponents/SearchSection.vue
  src/views/PortfolioListPage.vue
  src/views/ProjectListPage.vue
Labels: ✨ 개선 (enhancement), 🎨 디자인 (design)

#45 fix:유저검색기능수정
  src/api/search.js
  src/stores/techTagStore.js
  src/views/PortfolioListPage.vue
  src/views/ProjectListPage.vue
Labels: 🐞 버그 (bug)

#49 feat: 인기글 조회 수정, 피드백 모달 추가
  src/App.vue
  src/components/common/TechStackStatus.vue
  src/components/homeComponents/ProjectSection.vue
  src/components/layout/AppHeader.vue
  src/components/portfolioComponents/ProjectsSection.vue
  src/components/projectComponents/ProjectCard.vue
  src/components/projectComponents/ProjectHeader.vue
  src/components/projectComponents/TabNavigation.vue
  src/components/projectComponents/TeamInviteModal.vue
  src/components/projectComponents/TeamMemberRecommendation.vue
  src/components/recommendations/FeedbackModal.vue
  src/components/recommendations/ProjectRecommendationTab.vue
  src/components/recommendations/TeamMemberRecommendationTab.vue
  src/composables/useNotifications.js
  src/stores/userStore.js
  src/views/AIRecommendationsPage.vue
  src/views/ProjectDetailPage.vue
  src/views/ProjectManagePage.vue
Labels: 🐞 버그 (bug), ✨ 개선 (enhancement)

#50 feat/마감순정렬, 스케줄링 프로젝트 상태값변경
  src/components/portfolioComponents/ReviewSection.vue
  src/components/projectComponents/CommentItem.vue
  src/components/projectComponents/SortOptions.vue
  src/views/ProjectCreatePage.vue
  src/views/ProjectDetailPage.vue
  src/views/ProjectListPage.vue
Labels: 🐞 버그 (bug), ✨ 개선 (enhancement)

#51 Fix token storage
  package.json
  src/App.vue
  src/api/axios.js
  src/api/login.js
  src/api/portfolio.js
  src/components/layout/AppHeader.vue
  src/components/portfolioComponents/PortfolioHeader.vue
  src/composables/useNotifications.js
  src/router/index.js
  src/stores/userStore.js
  src/style.css
  src/views/EmailLoginPage.vue
  src/views/MyPortfolioPage.vue
  src/views/OAuth2Succcess.vue
  src/views/OAuthSuccess.vue
  src/views/PortfolioPage.vue
  src/views/ProjectListPage.vue
Labels: 🐞 버그 (bug), 🛠 리팩토링 (refactoring)
