Repository PotentialRadar/PR-Front, pull requests merged in 2025-09, with the labels that each got.

#60 Refactor profile img
  src/components/common/PaginationComponent.vue
  src/components/common/ProfileImage.vue
  src/components/common/README.md
  src/components/portfolio/ProjectSelectionModal.vue
  src/components/portfolioComponents/ProjectsSection.vue
  src/components/portfolioComponents/ReviewSection.vue
  src/components/recommendations/TeamMemberRecommendationTab.vue
  src/composables/useProfileImage.js
  src/views/FavoritesPage.vue
  src/views/MyPortfolioPage.vue
  src/views/MyProjectListPage.vue
  src/views/PortfolioListPage.vue
  src/views/ProjectListPage.vue
Labels: 🛠 리팩토링 (refactoring)

#62 feat: 페이지 간 동기화 개선
  index.html
  src/components/homeComponents/ProjectSection.vue
  src/components/homeComponents/StatsSection.vue
  src/components/projectComponents/TeamMemberRecommendation.vue
  src/components/recommendations/TeamMemberRecommendationTab.vue
  src/views/AIRecommendationsPage.vue
Labels: 🐞 버그 (bug), ✨ 개선 (enhancement)

#63 Refactor rediswith login
  public/default-avatar.svg
  src/components/common/ProfileImage.vue
  src/components/portfolioComponents/PortfolioHeader.vue
  src/components/portfolioComponents/SkillsSection.vue
  src/composables/useProfileImage.js
  src/stores/userStore.js
  src/views/MyPortfolioPage.vue
  src/views/ProfileEditPage.vue
  src/views/SignUpPage.vue
Labels: 🛠 리팩토링 (refactoring)

#64 정렬 기능 수정
  src/api/search.js
  src/views/PortfolioListPage.vue
  src/views/ProjectListPage.vue
Labels: 🐞 버그 (bug)

#65 엘라스틱서치 정렬 수정
  src/views/PortfolioListPage.vue
  src/views/ProjectListPage.vue
Labels: 🐞 버그 (bug)

#68 fix/detailpage
  src/components/portfolioComponents/PortfolioHeader.vue
  src/components/projectComponents/ProjectHeader.vue
  src/components/projectComponents/ProjectWorkContent.vue
  src/views/FavoritesPage.vue
  src/views/MyProjectListPage.vue
  src/views/ProjectDetailPage.vue
  src/views/ProjectListPage.vue
  src/views/ProjectManagePage.vue
Labels: 🐞 버그 (bug)

#69 포트폴리오 아바타 수정
  src/components/dashboard/SiderDashBoardLayout.vue
  src/components/portfolioComponents/PortfolioHeader.vue
  src/components/projectComponents/ProjectWorkContent.vue
  src/views/MyPortfolioPage.vue
  src/views/PortfolioListPage.vue
  src/views/PortfolioPage.vue
  src/views/ProfileEditPage.vue
  src/views/ProjectDetailPage.vue
Labels: 🐞 버그 (bug)

#70 Fix/project
  src/views/MyProjectListPage.vue
Labels: 🐞 버그 (bug)
